### ISSUE TITLE
Module not found error

### ISSUE THREAD

**Issue by zoraiz-ali** [zoraiz-ali/gym#2]
Hello Stroper111 please check this.
when i run this code

env = gym.make('robot-v1')
state_size = env.observation_space.shape[0]
action_size = env.action_space.n

ModuleNotFoundError come,

ModuleNotFoundError: No module named 'gym_robot.envs.helper'

**Comment by zoraiz-ali** [comment]
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-7e20befb6f2a> in <module>
      5 
      6 
----> 7 env = gym.make('robot-v1')
      8 state_size = env.observation_space.shape[0]
      9 action_size = env.action_space.n

~\anaconda3\lib\site-packages\gym-0.17.3-py3.8.egg\gym\envs\registration.py in make(id, **kwargs)
    143 
    144 def make(id, **kwargs):
--> 145     return registry.make(id, **kwargs)
    146 
    147 def spec(id):

~\anaconda3\lib\site-packages\gym-0.17.3-py3.8.egg\gym\envs\registration.py in make(self, path, **kwargs)
     88             logger.info('Making new env: %s', path)
     89         spec = self.spec(path)
---> 90         env = spec.make(**kwargs)
     91         # We used to have people override _reset/_step rather than
     92         # reset/step. Set _gym_disable_underscore_compat = True on

~\anaconda3\lib\site-packages\gym-0.17.3-py3.8.egg\gym\envs\registration.py in make(self, **kwargs)
     57             env = self.entry_point(**_kwargs)
     58         else:
---> 59             cls = load(self.entry_point)
     60             env = cls(**_kwargs)
     61 

~\anaconda3\lib\site-packages\gym-0.17.3-py3.8.egg\gym\envs\registration.py in load(name)
     16 def load(name):
     17     mod_name, attr_name = name.split(":")
---> 18     mod = importlib.import_module(mod_name)
     19     fn = getattr(mod, attr_name)
     20     return fn

~\anaconda3\lib\importlib\__init__.py in import_module(name, package)
    125                 break
    126             level += 1
--> 127     return _bootstrap._gcd_import(name[level:], package, level)
    128 
    129 

~\anaconda3\lib\importlib\_bootstrap.py in _gcd_import(name, package, level)

~\anaconda3\lib\importlib\_bootstrap.py in _find_and_load(name, import_)

~\anaconda3\lib\importlib\_bootstrap.py in _find_and_load_unlocked(name, import_)

~\anaconda3\lib\importlib\_bootstrap.py in _load_unlocked(spec)

~\anaconda3\lib\importlib\_bootstrap_external.py in exec_module(self, module)

~\anaconda3\lib\importlib\_bootstrap.py in _call_with_frames_removed(f, *args, **kwds)

~\anaconda3\lib\site-packages\gym_robot-0.3-py3.8.egg\gym_robot\envs\__init__.py in <module>
----> 1 from gym_robot.envs.robot_world import RobotWorld
      2 from gym_robot.envs.robot_env import RobotEnv

~\anaconda3\lib\site-packages\gym_robot-0.3-py3.8.egg\gym_robot\envs\robot_world.py in <module>
      4 #from typing import Tuple, Dict, List
      5 
----> 6 from gym_robot.envs.helper import constants, Size, Location, Square
      7 from typing import Dict, Tuple
      8 

ModuleNotFoundError: No module named 'gym_robot.envs.helper'

**Comment by Stroper111** [comment]
Checking
